config = {
    'exp_name' : 'ver_15',
    'epoch' : 100,
    'lr' : 1,
    'batch' : 128,
    'val_frequency' : 100,
    'test' : False,
    'resume_model' : './final_model/final_model.pth',
    'train_dataset' : './lmdb/ver_15/train_lmdb',
    'validation_dataset': './lmdb/ver_15/val_lmdb',
    'inference_dataset': './test',
    'schedule_frequency' : 10,
    'imageH' : 32,
    'imageW' : 256,
    'encoder' : 'resnet',
    'decoder' : 'transformer',
    'alpha_path' : './data/char_handwriting_Chinese.txt',
    'radical_path': './data/radical_all_Chinese.txt',
    'decompose_path': './data/decompose.txt',
    'pre-train_model': './pre_train_model/author_pre_train_model.pth',
    'stn': False,
    'constrain': False,
    'char_len' : 60,
}
