config = {
    'exp_name' : 'kid_ver_3_with_author_pre_train_model',
    'epoch' : 100,
    'lr' : 1,
    'batch' : 128,
    'val_frequency' : 100,
    'test' : False,
    'resume_model' : '',
    'train_dataset' : '/mnt/storage/kellen/lmdb/kid_data_ver_3/train_lmdb',
    'validation_dataset': '/mnt/storage/kellen/lmdb/kid_data_ver_3/val_lmdb',
    'inference_dataset': '',
    'schedule_frequency' : 10,
    'imageH' : 32,
    'imageW' : 256,
    'encoder' : 'resnet',
    'decoder' : 'transformer',
    'alpha_path' : './data/char_handwriting_Chinese.txt',
    'radical_path': './data/radical_all_Chinese.txt',
    'decompose_path': './data/decompose.txt',
    'pre-train_model': '/mnt/storage/kellen/pre_train_model/author_pre_train_model.pth',
    'stn': False,
    'constrain': False,
    'char_len' : 60,
}